microsoftgraph/msgraph-beta-sdk-php

.github/workflows/create-beta-pull-request.yml
PRs for the models are not getting auto-generated possible due to an issue on the pr-geration action.
This tries to create a possible fix.
=> Fix pipeline to generate PRs on model change

README.md, src/GraphConstants.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
=> Set Beta service library SDK version to 2.0.0-preview

composer.json, src/Graph.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
=> Adds Graph Core as a dependency

.github/workflows/update-docs.yml
Helps us easily resolve issues/conflicts with PHPDocs using manual intervention if needed
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
=> Allow manually triggering PHP docs update

src/Graph.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/599
=> Adds a Graph client constructor

README.md, composer.json, src/GraphConstants.php
Updates the Core version to use the soon to be latest graph-core (https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/55)
Also bumps beta's version
=> Bump Core dependency version

composer.json
part of https://github.com/microsoftgraph/msgraph-beta-sdk-php/issues/71
=> Bump graph core version

.github/workflows/bump-version.yml
following deprecation of create PR workflows in https://github.com/microsoftgraph/msgraph-beta-sdk-php/pull/141
=> Adds workflow to bump SDK version during generation runs

.github/workflows/bump-version.yml
fixes bug in https://github.com/microsoftgraph/msgraph-beta-sdk-php/pull/142
=> Bump SDK version workflow - Fix branch to push to

src/GraphRequestAdapter.php
depends on https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/92
=> Fix base graph request adapter argument order

composer.json, src/GraphServiceClient.php
part of https://github.com/microsoft/kiota-authentication-phpleague-php/issues/35
depends on https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/118
=> Support national clouds in graph client initialisation

src/GraphServiceClient.php, tests/GraphServiceClientTest.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1263
=> Init client with correct base URL when custom request adapter is used

phpstan.neon, src/GraphServiceClient.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1111
=> Bump PHPStan to level 9

composer.json
related to https://github.com/microsoftgraph/msgraph-sdk-php/issues/1367
=> Disable php-http discovery

.github/workflows/pr-validation.yml, README.md
Updates the badges at the top of the [README](https://github.com/microsoftgraph/msgraph-beta-sdk-php/tree/fix/readme-badges#readme) to reflect the latest version and some stats.
=> Update README badges

composer.json
=> - bumps patch version

README.md, composer.json, src/GraphServiceClient.php, tests/GraphServiceClientTest.php
part of https://github.com/microsoftgraph/msgraph-sdk-php/issues/1407
=> Add builder method to init graph client with custom authentication provider

.github/policies/msgraph-beta-sdk-php-branch-protection.yml
related #273 so we can delete dev
=> chore: minor edit to policy to trigger evaluation

src/GraphServiceClient.php, tests/GraphServiceClientTest.php
similar to https://github.com/microsoftgraph/msgraph-sdk-php/pull/1628
=> fix: Use provided national cloud as base URL and map it to the correct authentication endpoint

.github/workflows/pr-validation.yml, src/GraphRequestAdapter.php
=> PHP 8.4 compatibility
